### ISSUE TITLE
Scrum Retrospective

### ISSUE THREAD

**Issue by dsongUTS** [dsongUTS/Group-5-Assessment-Info-System-Development-#10]
As we near the completion of the assessment task, all group members are encouraged to reflect on their experience each and make a comment.

12613980 Daniel Song - I believe the overall attempt was satisfactory. Everyone was able to adapt to using the github platform fairly quickly despite its lack of familiarity, however there was some confusion in that everyone handled and formatted tasks in their own fashion. The iterative work and backlogs ensured that productivity would occur every work session and clear objectives established. Future improvements can involve clearer deadlines, more uniform adoption of the system by members and more frequent review of each task as they came out rather than toward the end.

**Comment by fsetyaputra** [comment]
13078175 Fajris Setyaputra - At first we were very confused because to do this assignment we were required to use GitHub for collaborating and some of us were not too familiar using it. But we managed to understand it and we created a branch based on each weekly backlog and also created issues and project boards to track our project progress. And also there was a little difficulty in combining all the branch to the master branch because there were some problems in using pull requests. Finally, we can all finish this project quite well.

**Comment by npudhota** [comment]
Nik Pudhota 12912491 - This was a unique project as we have never used Github in the context of creating a report. In the beginning it did take us a while to get familiar with using Github's features, but in the latter weeks we were able to use branches and issues to track our progress. Similar to using Trello, the project board was used to track our progress each week. We did face some issues when merging branches with conflicting files. Overall this project was challenging but gave us an opportunity to learn and employ Github's features.

**Comment by Zerexus** [comment]
13556042 Khurshid Manal - While I have used git and GitHub before this project was my first experience with issues, pull requests and the project board. Initially the group was very confused by these systems and we didn't use them. We exclusively used GitHub's branch functionality to organize and separate our work, but upon learning how the other features worked we were able to employ them to create an even more organized project. While this project was a bit difficult due to our lack of experience using GitHub we were all able to learn a lot.
